# Generated by Django 5.0.7 on 2024-09-17 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallistcustomization',
            name='stocked',
            field=models.BooleanField(default=True, verbose_name='Stocked Here'),
        ),
        migrations.AlterField(
            model_name='listcustomization',
            name='stocked',
            field=models.BooleanField(default=True, verbose_name='Stocked Here'),
        ),
    ]
