# Generated by Django 5.0.7 on 2024-09-17 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_historicallistcustomization_stocked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallistcustomization',
            name='Default Quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='listcustomization',
            name='Default Quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='listcustomization',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.category'),
        ),
        migrations.AlterField(
            model_name='listcustomization',
            name='default_unit_of_measure',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.unitofmeasure'
            ),
        ),
    ]
