# Generated by Django 5.0.7 on 2024-08-06 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_historicalunitofmeasure_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalunitofmeasure',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalunitofmeasure',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unitofmeasure',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unitofmeasure',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
