# Generated by Django 5.0.7 on 2024-08-26 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_historicallistitem_listitem_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="historicalcategory",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Category",
                "verbose_name_plural": "historical Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="historicallistcustomization",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical List Customization",
                "verbose_name_plural": "historical List Customizations",
            },
        ),
        migrations.AlterModelOptions(
            name="historicallistitem",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical List Item",
                "verbose_name_plural": "historical List Items",
            },
        ),
        migrations.AlterModelOptions(
            name="listcustomization",
            options={"verbose_name": "List Customization"},
        ),
        migrations.AlterModelOptions(
            name="listitem",
            options={"verbose_name": "List Item"},
        ),
    ]
