/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Shopping List API
 * Endpoints for interacting with the shopping list application
 * OpenAPI spec version: 1.0.0
 */
import type { ApiViewsItemCreateItemBodyId } from './apiViewsItemCreateItemBodyId'
import type { ApiViewsItemCreateItemBodyNotes } from './apiViewsItemCreateItemBodyNotes'

export type ApiViewsItemCreateItemBody = {
  category_id: string
  default_quantity?: number
  id?: ApiViewsItemCreateItemBodyId
  list_group_id: string
  name: string
  notes?: ApiViewsItemCreateItemBodyNotes
  photo?: Blob
  plural_name: string
  unit_of_measure_id: string
}
