/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Shopping List API
 * Endpoints for interacting with the shopping list application
 * OpenAPI spec version: 1.0.0
 */
import type { CategoryInId } from './categoryInId'

export interface CategoryIn {
  id?: CategoryInId
  name: string
  shopping_list_group_id: string
}
