/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Shopping List API
 * Endpoints for interacting with the shopping list application
 * OpenAPI spec version: 1.0.0
 */
import type { MinimizedCategorypOut } from './minimizedCategorypOut'
import type { ListItemOutwithDetails } from './listItemOutwithDetails'

export interface CategoryDetails {
  category: MinimizedCategorypOut
  items: ListItemOutwithDetails[]
}
