/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Shopping List API
 * Endpoints for interacting with the shopping list application
 * OpenAPI spec version: 1.0.0
 */
import type { ItemCreateId } from './itemCreateId'
import type { ItemCreateNotes } from './itemCreateNotes'

export interface ItemCreate {
  category_id: string
  default_quantity?: number
  id?: ItemCreateId
  list_group_id: string
  name: string
  notes?: ItemCreateNotes
  plural_name: string
  unit_of_measure_id: string
}
