/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Shopping List API
 * Endpoints for interacting with the shopping list application
 * OpenAPI spec version: 1.0.0
 */
import type { ListItemOutCreatedAt } from './listItemOutCreatedAt'
import type { ListItemOutCreatedBy } from './listItemOutCreatedBy'
import type { ListItemOutId } from './listItemOutId'
import type { ListItemOutUpdatedAt } from './listItemOutUpdatedAt'
import type { ListItemOutUpdatedBy } from './listItemOutUpdatedBy'

export interface ListItemOut {
  active: boolean
  completed: boolean
  created_at?: ListItemOutCreatedAt
  created_by?: ListItemOutCreatedBy
  id?: ListItemOutId
  item: string
  quantity?: number
  shopping_list_group: string
  updated_at?: ListItemOutUpdatedAt
  updated_by?: ListItemOutUpdatedBy
}
