/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Shopping List API
 * Endpoints for interacting with the shopping list application
 * OpenAPI spec version: 1.0.0
 */
import type { ItemOutMinimized } from './itemOutMinimized'

export interface ListItemOutwithDetails {
  active: boolean
  completed: boolean
  id: string
  item: ItemOutMinimized
  quantity: number
}
