/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Shopping List API
 * Endpoints for interacting with the shopping list application
 * OpenAPI spec version: 1.0.0
 */
import type { ListDetails } from './listDetails'
import type { MinimizedShoppingListGroupOut } from './minimizedShoppingListGroupOut'

export interface ShoppingListGroupDetails {
  lists: ListDetails[]
  shopping_list_group: MinimizedShoppingListGroupOut
}
