/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Shopping List API
 * Endpoints for interacting with the shopping list application
 * OpenAPI spec version: 1.0.0
 */
import type { ShoppingListGroupOutCreatedAt } from './shoppingListGroupOutCreatedAt'
import type { ShoppingListGroupOutCreatedBy } from './shoppingListGroupOutCreatedBy'
import type { ShoppingListGroupOutId } from './shoppingListGroupOutId'
import type { ShoppingListGroupOutUpdatedAt } from './shoppingListGroupOutUpdatedAt'
import type { ShoppingListGroupOutUpdatedBy } from './shoppingListGroupOutUpdatedBy'

export interface ShoppingListGroupOut {
  created_at?: ShoppingListGroupOutCreatedAt
  created_by?: ShoppingListGroupOutCreatedBy
  id?: ShoppingListGroupOutId
  name: string
  updated_at?: ShoppingListGroupOutUpdatedAt
  updated_by?: ShoppingListGroupOutUpdatedBy
}
