/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Shopping List API
 * Endpoints for interacting with the shopping list application
 * OpenAPI spec version: 1.0.0
 */
import type { ShoppingListInId } from './shoppingListInId'

export interface ShoppingListIn {
  id?: ShoppingListInId
  list_group_id: string
  name: string
}
