/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Shopping List API
 * Endpoints for interacting with the shopping list application
 * OpenAPI spec version: 1.0.0
 */
import type { ShoppingListOutCreatedAt } from './shoppingListOutCreatedAt'
import type { ShoppingListOutCreatedBy } from './shoppingListOutCreatedBy'
import type { ShoppingListOutId } from './shoppingListOutId'
import type { ShoppingListOutUpdatedAt } from './shoppingListOutUpdatedAt'
import type { ShoppingListOutUpdatedBy } from './shoppingListOutUpdatedBy'

export interface ShoppingListOut {
  created_at?: ShoppingListOutCreatedAt
  created_by?: ShoppingListOutCreatedBy
  id?: ShoppingListOutId
  list_group: string
  name: string
  updated_at?: ShoppingListOutUpdatedAt
  updated_by?: ShoppingListOutUpdatedBy
}
