/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Shopping List API
 * Endpoints for interacting with the shopping list application
 * OpenAPI spec version: 1.0.0
 */
import type { UnitOfMeasureOutCreatedAt } from './unitOfMeasureOutCreatedAt'
import type { UnitOfMeasureOutCreatedBy } from './unitOfMeasureOutCreatedBy'
import type { UnitOfMeasureOutId } from './unitOfMeasureOutId'
import type { UnitOfMeasureOutPluralName } from './unitOfMeasureOutPluralName'
import type { UnitOfMeasureOutUpdatedAt } from './unitOfMeasureOutUpdatedAt'
import type { UnitOfMeasureOutUpdatedBy } from './unitOfMeasureOutUpdatedBy'

export interface UnitOfMeasureOut {
  created_at?: UnitOfMeasureOutCreatedAt
  created_by?: UnitOfMeasureOutCreatedBy
  id?: UnitOfMeasureOutId
  name: string
  plural_name?: UnitOfMeasureOutPluralName
  updated_at?: UnitOfMeasureOutUpdatedAt
  updated_by?: UnitOfMeasureOutUpdatedBy
}
