/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Shopping List API
 * Endpoints for interacting with the shopping list application
 * OpenAPI spec version: 1.0.0
 */

export interface UserUpdate {
  email?: string
  first_name?: string
  last_name?: string
  password?: string
}
