/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Shopping List API
 * Endpoints for interacting with the shopping list application
 * OpenAPI spec version: 1.0.0
 */
import type { UserInFirstName } from './userInFirstName'
import type { UserInLastName } from './userInLastName'

export interface UserIn {
  email: string
  first_name: UserInFirstName
  last_name: UserInLastName
  password: string
}
