/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Shopping List API
 * Endpoints for interacting with the shopping list application
 * OpenAPI spec version: 1.0.0
 */
import type { UserSchemaId } from './userSchemaId'

export interface UserSchema {
  /** @maxLength 254 */
  email: string
  /** @maxLength 255 */
  first_name: string
  id?: UserSchemaId
  /** @maxLength 255 */
  last_name: string
}
